---
- name: Template sonar.properties
  template:
    src: sonar.properties.j2
    dest: "{{ sonarqube_home }}/conf/sonar.properties"
    owner: "{{ sonarqube_user }}"
    group: "{{ sonarqube_group }}"
    mode: '0644'
  notify: Restart SonarQube

- name: Create systemd service file
  copy:
    dest: "/etc/systemd/system/{{ sonarqube_service_name }}.service"
    content: |
      [Unit]
      Description=SonarQube service
      After=syslog.target network.target

      [Service]
      Type=forking
      ExecStart={{ sonarqube_home }}/bin/linux-x86-64/sonar.sh start
      ExecStop={{ sonarqube_home }}/bin/linux-x86-64/sonar.sh stop
      User={{ sonarqube_user }}
      Group={{ sonarqube_group }}
      Restart=always
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  notify: Reload systemd

- name: Enable and start SonarQube service
  systemd:
    name: "{{ sonarqube_service_name }}"
    enabled: true
    state: started