---
- name: Create group
  group:
    name: "{{ sonarqube_group }}"
    state: present

- name: Create user
  user:
    name: "{{ sonarqube_user }}"
    group: "{{ sonarqube_group }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Create installation directory
  file:
    path: "{{ sonarqube_install_dir }}"
    state: directory
    owner: "{{ sonarqube_user }}"
    group: "{{ sonarqube_group }}"

- name: Download SonarQube archive
  get_url:
    url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"
    dest: "/tmp/sonarqube-{{ sonarqube_version }}.zip"

- name: Unarchive SonarQube
  unarchive:
    src: "/tmp/sonarqube-{{ sonarqube_version }}.zip"
    dest: "{{ sonarqube_install_dir }}"
    remote_src: true