plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.Name
    prefix: tag
hostnames:
  - dns-name
filters:
  tag:Name: "web"
  hostname_variable: public_ip_address
  instance-state-name: running
